server:
  port: 8087

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://127.0.0.1:10087/eureka


spring:
  application:
    name: shop-web

  redis:
    database: 0
    password:
    port: 6379
    host: 127.0.0.1
